config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 
  unauthenticated :user do
    root to: 'splash#index'
  end

  authenticated :user do
    root "categories#index", as: :authenticated_root
  end
  
  resources :categories do
    resources :transactions
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Category
    can :create, Category

    can :read, Transaction
    can :create, Transaction

    return unless user.present?

    can :destroy, Category, user: user
    can :destroy, Transaction, user:
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }
  has_one_attached :icon

  def total_amount
    transactions.sum(:amount)
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories, dependent: :destroy

  validates :name, :amount, presence: true, length: { maximum: 255 }
  validates :amount, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.includes(:user, :transactions).order(created_at: :desc)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @categories = Category.includes(:user, :transactions).find(params['id'])
    redirect_to category_transactions_path(@category)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to root_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    puts plain: params
    @category = Category.find(params[:id])
    @category.destroy

    flash[:notice] = 'Category was successfully deleted'
    redirect_to root_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.includes(:user, :transactions).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:category_id, :name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_transaction, only: %i[show edit update destroy]

  # GET /transactions or /transactions.json
  def index
    @category = Category.includes(:user, :transactions).find(params['category_id'])
    @transactions = Transaction.includes(:user,
                                         :categories).where(category_id: params['category_id']).order(created_at: :desc)
  end

  # GET /transactions/1 or /transactions/1.json
  def show; end

  # GET /transactions/new
  def new
    @category = Category.find(params['category_id'])
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user_id = current_user.id

    respond_to do |format|
      if @transaction.save
        format.html do
          redirect_to category_transactions_path(transaction_params[:category_id]),
                      notice: 'Transaction was successfully created.'
        end
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    # puts plain: params
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    flash[:notice] = 'Transaction was successfully deleted.'
    redirect_to category_transactions_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.includes(:user, :categories).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:category_id, :name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/_category.html.erb
<section class= "category_card">
<%= image_tag category.icon, class:'icon'%>
<div class= "details">
<span class= "top_data">
<h2 class= "category_name"> <%= category.name %></h2>
<span class= "category_total"> <%= number_to_currency(category.total_amount)%></span>
</span>

 <span class="bottom_data">
      <time data="<%= category.created_at %>"><%= category.created_at.strftime("%e %B %Y") %></time>
      <% if can? :destroy, category %>
          <% if request.path != '/' %>
            <%= button_to 'Delete ', category_url(id: category.id), method: :delete,  data: {turbo: false}, class: 'btn' %>
          <%end%>
        <% else %>
        <span></span>
      <% end %>
    </span>
</div>
</section>

app/views/categories/_form.html.erb
<%= form_with(model: category, class:'new_category') do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "category-input">

  <%= form.text_field :name, autofocus: true, placeholder: "Category Name", required: true %>

  <%= form.file_field :icon,  placeholder: "Image or Icon", required: true %>
  
  </div>

  <div class= "actions">
    <%= form.submit class: "category_btn" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<header>
<h1>MoneyWallet</h1>
<%= button_to "Logout", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "btn bg-danger"  %>
</header>

<main>
 <% if @categories.any? %>
  <% @categories.each do |category| %>
  <%= link_to render(category), category_transactions_path(category), class: 'category_wrapper'%> 
<% end %> 
 <% else %>
 <p style="margin-top: 50px; text-align:center; color: orange; font-weight:bold;">
    There is no category added yet!
  </p>
<% end %>
</main>

<footer>
<%= link_to "Add a new category", new_category_path %>
</footer>

app/views/categories/new.html.erb
<header>

<%= link_to "Back", root_path, class: "back_btn"%>
<h1>New category</h1>
 <% if user_signed_in? %>
   <%= button_to "Logout", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "btn bg-danger"  %>
 <% end %>
</header>
<main>
<%= render "form", category: @category %>
</main>

<footer>
  <%= link_to "Back to categories", categories_path %>
</footer>

app/views/categories/show.html.erb
<header>

<%= link_to "Back", categories_path, class: "back_btn"%>
<h1>MoneyWallet</h1>
  <% if user_signed_in? %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn bg-danger" %>
  <% end %>
</header>


<%= render @category %>

<div class="category_actions">
  <%= link_to "Edit", edit_category_path(@category) %>
  <%= button_to "Destroy category", @category, method: :delete %>
</div>

<footer>
  <%= link_to "Add new transaction", new_category_transaction %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<section class="splash-page">
<h1 class= "tittle_app">MoneyWallet</h1>
<div class= "splash-actions">
<%= link_to 'Log-in', user_session_path, class: 'sign-in-btn' %>
</div>

<%= link_to 'Sign up', new_user_registration_path, class: 'sign-in-btns'%>
</section>

app/views/transactions/_form.html.erb
<%= form_for @transaction, url: category_transactions_path do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= 'input-fields'>
  <div class= input-wrapper>
    <%= form.label  "Choose Category"  %>
    <%= form.collection_select(:category_id, Category.all, :id, :name, {:prompt => 'Select a Category', :selected => @category.id }, { required: true })%>
  </div>  
  
  <div class= input-wrapper>
    <%= form.label  "Product"  %>
    <%= form.text_field :name, autofocus: true, placeholder: "Item name", required: true %>
  </div>  

  <div class= input-wrapper>
    <%= form.label  "Amount"  %>
    <%= form.number_field :amount, autofocus: true, step: 0.01, placeholder: "Amount", required: true %>
  </div>  
  

  </div>

  <div class= "actions">
    <%= form.submit class: "transaction-btn" %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div class= "transaction">
<span><%= transaction.name%></span>
<span><%= transaction.created_at.strftime("%e %B %Y") %></span>
<span> <%= number_to_currency(transaction.amount) %></span>
  <% if can? :destroy, transaction %>
     <%= button_to 'detele', category_transaction_path(id: transaction.id), method: :delete,  data: {turbo: false}, class: 'btn bg-danger' %>
  <% end %>
</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to transactions", category_transactions_path %>
</div>

app/views/transactions/index.html.erb
<header>
 <%= link_to "Back", root_path, class: 'back_btn'%>

 <h1>Transactions</h1>

  <% if user_signed_in? %>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "btn bg-danger"  %>
  <% end %>

</header>

<%= render partial: "categories/category", locals: {category: @category} %>

<div id="transactions">
  <% @transactions.each do |transaction| %>
    <%= render transaction %>
  <% end %>
</div>

<footer>
<%= link_to "Add Transaction", new_category_transaction_path %>
</footer>

app/views/transactions/new.html.erb
<header>
 <%= link_to "Back", category_transactions_path, class: 'back_btn' %>

 <h1> New Transaction</h1>

  <% if user_signed_in? %>
    <%= button_to "Logout", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "btn bg-danger"  %>
  <% end %>

</header>

<%= render partial: "form", locals: {transaction: @transaction} %>

<br>

<footer>
  <%= link_to "Back to transactions", category_transactions_path %>
</footer>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
   <%= link_to "Edit this transaction", edit_category_transaction_path %> |
  <%= link_to "Back to transactions", category_transactions_path %>
</div>